import fs from "fs";
import path from "path";
import { db } from "../db";

const DATA_DIR = process.env.SHIPYARD_DATA_DIR || path.join(process.cwd(), "data");
const CADDY_DIR = path.join(DATA_DIR, "caddy");
const CADDYFILE_PATH = path.join(CADDY_DIR, "Caddyfile");

export interface ProxyRoute {
  domain: string;
  targetPort: number;
  projectId: string;
  projectSlug: string;
  ssl: boolean;
}

/**
 * Regenerates Caddy reverse proxy configuration based on active projects and domains
 */
export async function syncProxyRoutes(): Promise<ProxyRoute[]> {
  if (!fs.existsSync(CADDY_DIR)) {
    fs.mkdirSync(CADDY_DIR, { recursive: true });
  }

  const projects = await db.projects.list();
  const routes: ProxyRoute[] = [];

  for (const proj of projects) {
    if (proj.status === "RUNNING" && proj.allocatedPort) {
      // Subdomain route (e.g. app-name.shipyard.local)
      routes.push({
        domain: `${proj.slug}.shipyard.local`,
        targetPort: proj.allocatedPort,
        projectId: proj.id,
        projectSlug: proj.slug,
        ssl: false,
      });

      // Custom domains
      if (proj.domains && proj.domains.length > 0) {
        for (const d of proj.domains) {
          routes.push({
            domain: d.domain,
            targetPort: proj.allocatedPort,
            projectId: proj.id,
            projectSlug: proj.slug,
            ssl: true,
          });
        }
      }
    }
  }

  // Generate Caddyfile syntax
  let caddyfileContent = `# Auto-generated by Shipyard Appliance Supervisor\n# DO NOT EDIT DIRECTLY\n\n`;
  caddyfileContent += `{\n  admin 0.0.0.0:2019\n  auto_https off\n}\n\n`;

  for (const route of routes) {
    caddyfileContent += `${route.domain} {\n  reverse_proxy localhost:${route.targetPort}\n}\n\n`;
  }

  fs.writeFileSync(CADDYFILE_PATH, caddyfileContent, "utf8");
  return routes;
}
