import fs from "fs";
import path from "path";
import { exec } from "child_process";
import { db } from "../db";

const DATA_DIR = process.env.SHIPYARD_DATA_DIR || path.join(process.cwd(), "data");
const CADDY_DIR = path.join(DATA_DIR, "caddy");
const CADDYFILE_PATH = path.join(CADDY_DIR, "Caddyfile");

export interface ProxyRoute {
  domain: string;
  targetPort: number;
  containerName?: string;
  projectId: string;
  projectSlug: string;
  ssl: boolean;
}

/**
 * Regenerates Caddy reverse proxy configuration based on active projects,
 * subdomains, and custom domains, then triggers live Caddy reload.
 */
export async function syncProxyRoutes(): Promise<ProxyRoute[]> {
  if (!fs.existsSync(CADDY_DIR)) {
    fs.mkdirSync(CADDY_DIR, { recursive: true });
  }

  const projects = await db.projects.list();
  const routes: ProxyRoute[] = [];
  const baseDomain = process.env.SHIPYARD_BASE_DOMAIN?.trim() || "";

  for (const proj of projects) {
    if (proj.status === "RUNNING" && proj.allocatedPort) {
      const containerName = proj.containerId ? proj.containerId : `shipyard-${proj.slug}`;

      // Subdomain route (if base domain is configured e.g. apps.myvps.com or 142.93.10.15.nip.io)
      if (baseDomain) {
        routes.push({
          domain: `${proj.slug}.${baseDomain}`,
          targetPort: proj.allocatedPort,
          containerName,
          projectId: proj.id,
          projectSlug: proj.slug,
          ssl: !baseDomain.includes("localhost") && !baseDomain.includes("127.0.0.1"),
        });
      } else {
        // Fallback local virtual host
        routes.push({
          domain: `${proj.slug}.local`,
          targetPort: proj.allocatedPort,
          containerName,
          projectId: proj.id,
          projectSlug: proj.slug,
          ssl: false,
        });
      }

      // Custom domains configured by user
      if (proj.domains && proj.domains.length > 0) {
        for (const d of proj.domains) {
          routes.push({
            domain: d.domain,
            targetPort: proj.allocatedPort,
            containerName,
            projectId: proj.id,
            projectSlug: proj.slug,
            ssl: true,
          });
        }
      }
    }
  }

  // Generate production Caddyfile
  let caddyfile = `# ============================================================\n`;
  caddyfile += `# Auto-generated by Shipyard Web Server Supervisor\n`;
  caddyfile += `# Synchronized: ${new Date().toISOString()}\n`;
  caddyfile += `# ============================================================\n\n`;

  caddyfile += `{\n`;
  caddyfile += `  admin 0.0.0.0:2019\n`;
  caddyfile += `  auto_https disable_redirects\n`;
  caddyfile += `}\n\n`;

  // Control Plane routing for port 80 / main dashboard
  caddyfile += `:80 {\n`;
  caddyfile += `  reverse_proxy shipyard-app:3000 {\n`;
  caddyfile += `    header_up Host {host}\n`;
  caddyfile += `    header_up X-Real-IP {remote_host}\n`;
  caddyfile += `    header_up X-Forwarded-For {remote_host}\n`;
  caddyfile += `    header_up X-Forwarded-Proto {scheme}\n`;
  caddyfile += `  }\n`;
  caddyfile += `}\n\n`;

  // Route each application
  for (const route of routes) {
    caddyfile += `${route.domain} {\n`;
    // Attempt container direct routing via docker network first, fallback to host-gateway
    caddyfile += `  reverse_proxy host.docker.internal:${route.targetPort} {\n`;
    caddyfile += `    header_up Host {host}\n`;
    caddyfile += `    header_up X-Real-IP {remote_host}\n`;
    caddyfile += `    header_up X-Forwarded-For {remote_host}\n`;
    caddyfile += `    header_up X-Forwarded-Proto {scheme}\n`;
    caddyfile += `  }\n`;
    caddyfile += `}\n\n`;
  }

  fs.writeFileSync(CADDYFILE_PATH, caddyfile, "utf8");

  // Attempt live hot-reload of Caddy proxy without restarting container
  try {
    exec(
      "docker exec shipyard-proxy caddy reload --config /var/lib/shipyard/data/caddy/Caddyfile",
      { timeout: 5000 },
      (err) => {
        if (err) {
          // If docker exec fails, try Caddy admin REST API
          try {
            fetch("http://shipyard-proxy:2019/load", {
              method: "POST",
              headers: { "Content-Type": "text/caddyfile" },
              body: caddyfile,
            }).catch(() => {});
          } catch {}
        }
      }
    );
  } catch {}

  return routes;
}
