import { BuildpackType } from "@/types";
import { BuildpackDetectionResult } from "./types";

/**
 * Analyzes repository files to determine the optimal build strategy
 */
export function detectBuildpack(
  fileList: string[],
  packageJson?: {
    scripts?: Record<string, string>;
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  },
  requirementsTxt?: string
): BuildpackDetectionResult {
  const normalizedFiles = fileList.map((f) => f.toLowerCase().replace(/^\.?\//, ""));

  // 1. Explicit Dockerfile
  if (normalizedFiles.includes("dockerfile")) {
    return {
      type: "DOCKERFILE",
      confidence: 1.0,
      reason: "Found root Dockerfile",
      suggestedPort: 3000,
    };
  }

  // 2. Node.js / Next.js
  if (normalizedFiles.includes("package.json")) {
    const isNext =
      packageJson?.dependencies?.next ||
      packageJson?.devDependencies?.next ||
      normalizedFiles.some((f) => f.startsWith("next.config"));

    const isVite =
      packageJson?.dependencies?.vite ||
      packageJson?.devDependencies?.vite ||
      normalizedFiles.some((f) => f.startsWith("vite.config"));

    if (isNext) {
      return {
        type: "NODEJS",
        confidence: 0.95,
        reason: "Detected Next.js project via package.json",
        suggestedPort: 3000,
        suggestedBuildCommand: "npm run build",
        suggestedRunCommand: "npm start",
        generatedDockerfile: generateNextJsDockerfile(),
      };
    }

    if (isVite) {
      return {
        type: "NODEJS",
        confidence: 0.9,
        reason: "Detected Vite/React project via package.json",
        suggestedPort: 80,
        suggestedBuildCommand: "npm run build",
        suggestedRunCommand: "serve -s dist -l 80",
        generatedDockerfile: generateViteDockerfile(),
      };
    }

    return {
      type: "NODEJS",
      confidence: 0.85,
      reason: "Detected Node.js project via package.json",
      suggestedPort: 3000,
      suggestedBuildCommand: packageJson?.scripts?.build ? "npm run build" : undefined,
      suggestedRunCommand: packageJson?.scripts?.start ? "npm start" : "node index.js",
      generatedDockerfile: generateStandardNodeDockerfile(),
    };
  }

  // 3. Python (FastAPI / Flask / Django)
  if (
    normalizedFiles.includes("requirements.txt") ||
    normalizedFiles.includes("pyproject.toml") ||
    normalizedFiles.includes("pipfile")
  ) {
    const isFastAPI = requirementsTxt?.toLowerCase().includes("fastapi");
    const isDjango = requirementsTxt?.toLowerCase().includes("django");

    let port = 8000;
    let runCmd = "uvicorn main:app --host 0.0.0.0 --port 8000";

    if (isDjango) {
      port = 8000;
      runCmd = "gunicorn --bind 0.0.0.0:8000 wsgi:application";
    } else if (!isFastAPI && requirementsTxt?.toLowerCase().includes("flask")) {
      port = 5000;
      runCmd = "gunicorn --bind 0.0.0.0:5000 app:app";
    }

    return {
      type: "PYTHON",
      confidence: 0.9,
      reason: `Detected Python project with ${isFastAPI ? "FastAPI" : isDjango ? "Django" : "Python dependencies"}`,
      suggestedPort: port,
      suggestedRunCommand: runCmd,
      generatedDockerfile: generatePythonDockerfile(runCmd, port),
    };
  }

  // 4. Static HTML / Web
  if (normalizedFiles.includes("index.html")) {
    return {
      type: "STATIC",
      confidence: 0.8,
      reason: "Detected static website via root index.html",
      suggestedPort: 80,
      generatedDockerfile: generateStaticDockerfile(),
    };
  }

  return {
    type: "CUSTOM",
    confidence: 0.1,
    reason: "No standard application markers found; custom configuration required",
    suggestedPort: 8080,
  };
}

/**
 * Multi-stage Dockerfile for Next.js applications
 */
export function generateNextJsDockerfile(): string {
  return `# Generated by Shipyard Auto-Buildpack
FROM node:20-alpine AS base
WORKDIR /app
RUN apk add --no-cache libc6-compat

FROM base AS deps
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./
RUN \\
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \\
  elif [ -f package-lock.json ]; then npm ci; \\
  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \\
  else npm install; \\
  fi

FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM base AS runner
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
USER nextjs
EXPOSE 3000
CMD ["npm", "start"]
`;
}

/**
 * Dockerfile for Vite / SPA applications
 */
export function generateViteDockerfile(): string {
  return `# Generated by Shipyard Auto-Buildpack
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci || npm install
COPY . .
RUN npm run build

FROM nginx:alpine-slim
COPY --from=builder /app/dist /usr/share/nginx/html
COPY <<EOF /etc/nginx/conf.d/default.conf
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files \\$uri \\$uri/ /index.html;
    }
}
EOF
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * Standard Node.js application Dockerfile
 */
export function generateStandardNodeDockerfile(): string {
  return `# Generated by Shipyard Auto-Buildpack
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --only=production || npm install --production
COPY . .
EXPOSE 3000
CMD ["node", "index.js"]
`;
}

/**
 * Python application Dockerfile
 */
export function generatePythonDockerfile(runCommand: string, port: number): string {
  return `# Generated by Shipyard Auto-Buildpack
FROM python:3.11-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
COPY requirements.txt* pyproject.toml* ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(runCommand.split(" "))}
`;
}

/**
 * Static site Nginx Dockerfile
 */
export function generateStaticDockerfile(): string {
  return `# Generated by Shipyard Auto-Buildpack
FROM nginx:alpine-slim
COPY . /usr/share/nginx/html
COPY <<EOF /etc/nginx/conf.d/default.conf
server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files \\$uri \\$uri/ /index.html;
    }
}
EOF
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}
